### ISSUE TITLE
Android performance

### ISSUE THREAD

**Issue by FunnyDevs** [MichaelRocks/lightsaber#1]
Hi! I would like to use this library on my Android project. I would like to know if it uses reflection to inject fields and if it has better performance avoiding private fields.

Thanks

**Comment by MichaelRocks** [comment]
Hi! No, this library doesn't use reflection at all. Instead it generates and modifies byte-code at compile time. And if you use a private field for injection it's converted to public.

However, I should inform you that API is not stable yet and some breaking changes are coming.

**Comment by FunnyDevs** [comment]
Ok, thanks for information. However i'll try it!

**Comment by MichaelRocks** [comment]
Great! Feel free to ask me if you have any questions.
