### ISSUE TITLE
Potential Documentation issues

### ISSUE THREAD

**Issue by markuspg** [MichaelRocks/lightsaber#9]
Hi @MichaelRocks,

thank you for supplying this library. I'm a Kotlin starter and therefore slightly wrestling with getting Lightsaber up and running.

In the documentation I read of `@Import` and `@Provide`. Both I could not find but in examples `@Provides`. With these my code is compiling but not running.

Additionally the 0.12.0-beta dependendy in the classpath does not seem to exist in the repositories yet. On the master branch the correct 0.11.1-beta is listed. Perhaps you could make the master branch the default one to make using your project easier for starters?

**Comment by MichaelRocks** [comment]
Hi @markuspg,

Thank you for reporting the issue. Actually the documentation is correct for the code from `develop` branch. I switched the default branch to `master`, so now everything should be fine.
